name: ishangavidusha
description: Ishanga Vidusha's Portfolio Website.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.2
  go_router: ^3.0.1
  url_launcher: ^6.0.20
  shared_preferences: ^2.0.13
  intl: ^0.17.0
  google_fonts: ^2.3.1
  font_awesome_flutter: ^9.2.0
  animated_text_kit: ^4.2.1
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
